# Generated by Django 4.2.11 on 2024-03-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('quota_limit_reached', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=50, unique=True)),
                ('title', models.TextField(max_length=255)),
                ('description', models.TextField()),
                ('publish_time', models.DateTimeField()),
                ('thumbnail_url', models.URLField()),
            ],
        ),
    ]
