# Generated by Django 4.2.11 on 2024-03-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikeys',
            name='quota_limit_reached',
            field=models.BooleanField(default=False),
        ),
    ]
